### ISSUE TITLE
Create React DatePicker component

### ISSUE THREAD

**Issue by rego-devil** [Nevatrip/cart#4]
![image](https://user-images.githubusercontent.com/25372977/51609492-5284cb00-1f2b-11e9-814a-541ef4602c3e.png)

![image](https://user-images.githubusercontent.com/25372977/51609515-62041400-1f2b-11e9-9ab4-2baac4ac5458.png)

**Comment by Realetive** [comment]
Example on https://github.com/Nevatrip/cart/tree/feature/calendar-component-#4
